---
passgen_source_dir: .
passgen_install_dir: /srv/passgen
passgen_user: cwygoda
passgen_group: www-data
passgen_socket_file: /srv/passgen/uwsgi.sock
passgen_processes: 2
passgen_threads: 2
passgen_virtualenv_name: passgen
passgen_virtualenv_dir: /home/cwygoda/.pyenv/versions/{{ passgen_virtualenv_name}}
passgen_uwsgi_file: /srv/passgen/uwsgi.ini
passgen_server_name: '*'
passgen_static_dir: /srv/passgen/code/kinderstadt_passgen/static
passgen_url_path: /
passgen_supervisord_file: /etc/supervisor/conf.d/passgen.conf
passgen_log_dir: /srv/passgen/logs
passgen_server_name: localhost
